# Generated by Django 3.1.4 on 2020-12-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FederalState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_code', models.CharField(max_length=2)),
                ('spec_yield', models.IntegerField()),
            ],
            options={
                'ordering': ['letter_code'],
            },
        ),
    ]
